"""initial schema

Revision ID: d955b0805dd1
Revises: 
Create Date: 2026-08-16 14:23:59.848857

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd955b0805dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_states_code'), 'event_states', ['code'], unique=True)
    op.create_table('event_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('is_rework', sa.Boolean(), nullable=False),
    sa.Column('is_release', sa.Boolean(), nullable=False),
    sa.Column('is_revision_bump', sa.Boolean(), nullable=False),
    sa.Column('moves_quantity', sa.Boolean(), nullable=False),
    sa.Column('requires_item_step', sa.Boolean(), nullable=False),
    sa.Column('requires_reason_code', sa.Boolean(), nullable=False),
    sa.Column('counts_toward_completion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_types_code'), 'event_types', ['code'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('client', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('reason_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reason_codes_code'), 'reason_codes', ['code'], unique=True)
    op.create_table('route_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_route_code_version')
    )
    op.create_index(op.f('ix_route_templates_code'), 'route_templates', ['code'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_station', sa.Boolean(), nullable=False),
    sa.Column('requires_external_po', sa.Boolean(), nullable=False),
    sa.Column('allows_partial_qty', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_code'), 'stages', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('drawing_revision', sa.String(length=32), nullable=False),
    sa.Column('target_release_date', sa.Date(), nullable=True),
    sa.Column('route_template_id', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('released_revision', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_template_id'], ['route_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_index(op.f('ix_items_project_id'), 'items', ['project_id'], unique=False)
    op.create_table('route_template_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_template_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['route_template_id'], ['route_templates.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_template_id', 'seq', name='uq_route_step_seq')
    )
    op.create_index(op.f('ix_route_template_steps_route_template_id'), 'route_template_steps', ['route_template_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_index(op.f('ix_stations_stage_id'), 'stations', ['stage_id'], unique=False)
    op.create_table('item_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'seq', name='uq_item_step_seq')
    )
    op.create_index(op.f('ix_item_steps_item_id'), 'item_steps', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_steps_stage_id'), 'item_steps', ['stage_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('item_step_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('event_type_id', sa.Uuid(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason_code_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('supersedes_event_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_step_id'], ['item_steps.id'], ),
    sa.ForeignKeyConstraint(['reason_code_id'], ['reason_codes.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['event_states.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['supersedes_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_item_id'), 'events', ['item_id'], unique=False)
    op.create_index('ix_events_item_occurred', 'events', ['item_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_item_step_id'), 'events', ['item_step_id'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_received_at'), 'events', ['received_at'], unique=False)
    op.create_index(op.f('ix_events_station_id'), 'events', ['station_id'], unique=False)
    op.create_index('ix_events_station_occurred', 'events', ['station_id', 'occurred_at'], unique=False)
    op.create_index('ix_events_step_occurred', 'events', ['item_step_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_supersedes_event_id'), 'events', ['supersedes_event_id'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_supersedes_event_id'), table_name='events')
    op.drop_index('ix_events_step_occurred', table_name='events')
    op.drop_index('ix_events_station_occurred', table_name='events')
    op.drop_index(op.f('ix_events_station_id'), table_name='events')
    op.drop_index(op.f('ix_events_received_at'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_item_step_id'), table_name='events')
    op.drop_index('ix_events_item_occurred', table_name='events')
    op.drop_index(op.f('ix_events_item_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_item_steps_stage_id'), table_name='item_steps')
    op.drop_index(op.f('ix_item_steps_item_id'), table_name='item_steps')
    op.drop_table('item_steps')
    op.drop_index(op.f('ix_stations_stage_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_route_template_steps_route_template_id'), table_name='route_template_steps')
    op.drop_table('route_template_steps')
    op.drop_index(op.f('ix_items_project_id'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stages_code'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_route_templates_code'), table_name='route_templates')
    op.drop_table('route_templates')
    op.drop_index(op.f('ix_reason_codes_code'), table_name='reason_codes')
    op.drop_table('reason_codes')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_event_types_code'), table_name='event_types')
    op.drop_table('event_types')
    op.drop_index(op.f('ix_event_states_code'), table_name='event_states')
    op.drop_table('event_states')
    # ### end Alembic commands ###
